import { GDGEvent, CarpoolPin, Ticket, UserProfile } from './types';

export const INITIAL_EVENTS: GDGEvent[] = [
  // UPCOMING FLAGSHIP DEVFEST
  {
    id: 'cloud-devfest-2026',
    title: 'Cloud DevFest 2026',
    tagline: 'The Flagship Google Developer Community Summit of the Year!',
    description: 'Cloud DevFest Islamabad 2026 is the largest annual tech gathering bringing together 2,000+ developers, cloud architects, student innovators, and Google Experts. Featuring keynotes on Generative AI, Firebase Genkit, Kubernetes, and Cloud Native Architecture with interactive carpool matching and instant CNIC QR gate entry.',
    date: 'Dec 12, 2026',
    time: '09:00 AM - 05:30 PM PKT',
    venue: 'Pak-China Friendship Centre, Garden Avenue, Islamabad',
    category: 'Cloud',
    status: 'Upcoming',
    registrationType: 'Free registration',
    capacity: 2000,
    registeredCount: 1140,
    bannerImg: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/Bevy%20Thumbnail_mhZInhY.png',
    speakers: [
      { name: 'Dr. Sarah Ahmed', role: 'Google Developer Expert (Cloud)', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80', company: 'Google Cloud' },
      { name: 'Ali Raza', role: 'Staff Software Engineer', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80', company: 'GDG Islamabad Core Lead' }
    ]
  },

  // EXACT PAST & UPCOMING EVENTS WITH OFFICIAL CLOUDINARY THUMBNAILS & METADATA FROM USER SNAPSHOT

  {
    id: 'build-next-beyond-independence',
    title: 'Build NEXT - Beyond Independence',
    tagline: 'Scaling Tech Ecosystems & Next-Gen Cloud Solutions',
    description: 'Empowering local tech leaders and startup builders to leverage Google Cloud, Serverless compute, and microservice architectures.',
    date: 'Aug 15, 2026',
    time: '02:00 PM - 06:00 PM PKT',
    venue: 'GDG CLOUD Islamabad, National Incubation Center',
    category: 'Web',
    status: 'Upcoming',
    registrationType: 'External registration',
    capacity: 500,
    registeredCount: 412,
    bannerImg: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/blob_YX8e2zu',
    speakers: []
  },
  {
    id: 'build-with-ai-telenor-velocity',
    title: 'Build With AI – Telenor | Velocity',
    tagline: 'Hands-on Generative AI Hacklab & Google Gemini Studio',
    description: 'Co-hosted with Telenor Velocity. Developers hack with Gemini API, Vertex AI, and build real-time civic products.',
    date: 'Jun 18, 2026',
    time: '10:00 AM - 04:00 PM PKT',
    venue: 'Telenor 345 Campus, Islamabad',
    category: 'AI / ML',
    status: 'Upcoming',
    registrationType: 'Free registration',
    capacity: 450,
    registeredCount: 390,
    bannerImg: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/blob_5WdWAjY',
    speakers: []
  },
  {
    id: 'build-with-ai-kickstart-cluster',
    title: 'Build With AI – Kickstart | Cluster',
    tagline: 'Prompt Engineering & LLM Orchestration with Firebase Genkit',
    description: 'An intensive workshop teaching developers how to integrate Gemini 1.5 Pro into production web apps.',
    date: 'Jun 6, 2026',
    time: '03:00 PM - 06:00 PM PKT',
    venue: 'Kickstart Co-working Space, I-9 Islamabad',
    category: 'AI / ML',
    status: 'Upcoming',
    registrationType: 'Free registration',
    capacity: 300,
    registeredCount: 280,
    bannerImg: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/blob_Cs51YpV',
    speakers: []
  },
  {
    id: 'build-with-ai-based-co-working',
    title: 'Build With AI – Based Co Working',
    tagline: 'Machine Learning Models & Data Pipelines on GCP',
    description: 'Community tech talk on deploying Vertex AI pipelines and vector databases for RAG.',
    date: 'May 17, 2026',
    time: '04:00 PM - 07:00 PM PKT',
    venue: 'Based Co-Working, F-11 Markaz Islamabad',
    category: 'AI / ML',
    status: 'Past',
    registrationType: 'Free registration',
    capacity: 200,
    registeredCount: 200,
    bannerImg: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/blob_pHjbcfB',
    speakers: []
  },
  {
    id: 'aik-nayi-soch-iwd-2026',
    title: "Aik Nayi Soch (International Women's Day 2026)",
    tagline: 'Women Techmakers Islamabad Annual Conference',
    description: 'Celebrating women leadership in cloud, software engineering, AI, and startup entrepreneurship across Pakistan.',
    date: 'Apr 11, 2026',
    time: '10:00 AM - 04:00 PM PKT',
    venue: 'FAST-NUCES Auditorium, Islamabad',
    category: 'Web',
    status: 'Past',
    registrationType: 'Free registration',
    capacity: 600,
    registeredCount: 600,
    bannerImg: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/Event%20Profile%20%281%29_cXb1R3S.jpg',
    speakers: []
  },
  {
    id: 'cloud-devfest-25',
    title: 'Cloud Devfest 25',
    tagline: 'GDG Cloud Islamabad Flagship DevFest 2025 Edition',
    description: 'Over 1,200 attendees joined for GDG Cloud DevFest 2025 covering Android, Flutter, Cloud, and Generative AI.',
    date: 'Dec 13, 2025',
    time: '09:00 AM - 05:00 PM PKT',
    venue: 'Pak-China Friendship Centre, Islamabad',
    category: 'Cloud',
    status: 'Past',
    registrationType: 'Free registration',
    capacity: 1200,
    registeredCount: 1200,
    bannerImg: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/Bevy%20Thumbnail_mhZInhY.png',
    speakers: []
  },
  {
    id: 'vibe-coding-firebase-studio',
    title: 'Vibe Coding with Firebase Studio',
    tagline: 'Next-gen Rapid App Prototyping with Firebase & AI',
    description: 'Hands-on session on building full-stack reactive applications in record time using Firebase Data Connect & Firestore.',
    date: 'Oct 1, 2025',
    time: '03:00 PM - 06:00 PM PKT',
    venue: 'NUST SEECS Lab, Islamabad',
    category: 'Web',
    status: 'Past',
    registrationType: 'Free registration',
    capacity: 350,
    registeredCount: 350,
    bannerImg: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/GDG_Bevy_DefaultEventThumbnail_2_va1kAS9.png',
    speakers: []
  },
  {
    id: 'google-cloud-next-extended',
    title: 'GOOGLE CLOUD NEXT EXTENDED',
    tagline: 'Keynote Replay, Live Demos & GCP Architecture Breakouts',
    description: 'Official GDG Cloud Islamabad extended watch party and local tech talks breaking down announcements from Google Cloud Next.',
    date: 'Aug 2, 2025',
    time: '02:00 PM - 06:00 PM PKT',
    venue: 'Islamabad Club Auditorium',
    category: 'Cloud',
    status: 'Past',
    registrationType: 'External registration',
    capacity: 400,
    registeredCount: 400,
    bannerImg: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/Bevy%20Event%20Cover_00Dm7HM.png',
    speakers: []
  },
  {
    id: 'gdg-cloud-next-pre-event-workshop',
    title: 'GDG Cloud Next Pre-Event - Workshop with Googlers',
    tagline: 'Hands-on Cloud Labs & Mentorship with Google Engineers',
    description: 'Exclusive pre-event technical workshop with Googlers exploring Kubernetes, GCP Cloud Run, and AI pipelines.',
    date: 'Jul 10, 2025',
    time: '02:00 PM - 05:00 PM PKT',
    venue: 'FAST-NUCES Auditorium, Islamabad',
    category: 'Cloud',
    status: 'Past',
    registrationType: 'Free registration',
    capacity: 300,
    registeredCount: 300,
    bannerImg: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/blob_qPdGUJU',
    speakers: []
  },
  {
    id: 'build-with-ai-red-buffer',
    title: 'Build with AI - Red Buffer',
    tagline: 'Building Enterprise LLM Agents & Generative Workflows',
    description: 'Technical deep dive with Red Buffer engineers on deploying LLM applications with Google AI Studio.',
    date: 'Jun 14, 2025',
    time: '03:00 PM - 06:00 PM PKT',
    venue: 'Red Buffer HQ, Islamabad',
    category: 'AI / ML',
    status: 'Past',
    registrationType: 'Free registration',
    capacity: 250,
    registeredCount: 250,
    bannerImg: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/contentbuilder/GDG_Bevy_DefaultEventThumbnail_2_va1kAS9.png',
    speakers: []
  },
  {
    id: 'build-with-ai-folio3',
    title: 'Build with AI - Folio3',
    tagline: 'AI Application Architecture on Google Cloud',
    description: 'Hands-on coding lab co-hosted with Folio3 software engineers focusing on Vertex AI Search & Conversation.',
    date: 'May 31, 2025',
    time: '10:00 AM - 02:00 PM PKT',
    venue: 'Folio3 Office, Islamabad',
    category: 'AI / ML',
    status: 'Past',
    registrationType: 'Free registration',
    capacity: 200,
    registeredCount: 200,
    bannerImg: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/Folio%202_sa1r4Bc.png',
    speakers: []
  },
  {
    id: 'build-with-ai-telenor',
    title: 'Build with AI - Telenor',
    tagline: 'Telecom Data Innovation & GenAI Agents',
    description: 'Exploring LLM use cases in telecommunications, customer support bots, and real-time processing.',
    date: 'Apr 23, 2025',
    time: '02:00 PM - 05:00 PM PKT',
    venue: 'Telenor 345 Campus, Islamabad',
    category: 'AI / ML',
    status: 'Past',
    registrationType: 'Free registration',
    capacity: 350,
    registeredCount: 350,
    bannerImg: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/Telenor%202_7pjxIiY.png',
    speakers: []
  }
];

export const INITIAL_CARPOOL_PINS: CarpoolPin[] = [
  {
    id: 'cp-1',
    userId: 'usr-1',
    userName: 'Usman Chaudhry',
    userCnic: '61101-1234567-1',
    phone: '0300-5551234',
    lat: 33.6844,
    lng: 73.0479,
    areaName: 'F-7 Markaz (Near Safa Gold Mall), Islamabad',
    seats: 3,
    departureTime: '08:15 AM (DevFest Day)',
    vehicleInfo: 'Honda Civic (White) - ICT-789',
    genderPreference: 'Anyone',
    note: 'Leaving early to grab front row seats at DevFest Pak-China Centre! Happy to pick up attendees near F-6 / F-7.',
    createdAt: '2026-09-01',
    messages: [
      {
        id: 'msg-1',
        carpoolId: 'cp-1',
        senderId: 'usr-2',
        senderName: 'Ayesha Tariq',
        senderCnic: '37405-9876543-2',
        text: 'Hi Usman! I am standing near Safa Mall entrance, can you pick me up at 8:15 AM?',
        timestamp: '08:02 AM'
      }
    ]
  },
  {
    id: 'cp-2',
    userId: 'usr-2',
    userName: 'Ayesha Tariq',
    userCnic: '37405-9876543-2',
    phone: '0333-8884321',
    lat: 33.5971,
    lng: 73.0458,
    areaName: 'Commercial Market, Satellite Town, Rawalpindi',
    seats: 2,
    departureTime: '08:00 AM (DevFest Day)',
    vehicleInfo: 'Toyota Vitz (Red)',
    genderPreference: 'Female Only',
    note: 'Offering ride for female developers attending GDG DevFest Cloud Summit from Pindi.',
    createdAt: '2026-09-01',
    messages: []
  },
  {
    id: 'cp-3',
    userId: 'usr-3',
    userName: 'Bilal Ahmed',
    userCnic: '61101-4567890-3',
    phone: '0312-9998877',
    lat: 33.6492,
    lng: 72.9836,
    areaName: 'G-13/1 Cyber Heights, Islamabad',
    seats: 4,
    departureTime: '08:30 AM',
    vehicleInfo: 'Suzuki Swift (Silver)',
    genderPreference: 'Anyone',
    note: 'Going via Srinagar Highway directly to Pak-China Friendship Centre.',
    createdAt: '2026-09-01',
    messages: []
  }
];

export const DEMO_USERS: Record<string, UserProfile> = {
  USER: {
    id: 'usr-demo-attendee',
    name: 'Sarmad Gardezi',
    cnic: '61101-7788990-1',
    email: 'sarmad.developer@gdg.community',
    phone: '0301-1234567',
    role: 'USER',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    registeredEvents: ['cloud-devfest-2026'],
    carpoolOptIn: true,
    carpoolLocation: {
      lat: 33.6844,
      lng: 73.0479,
      addressName: 'F-7 Markaz, Islamabad',
      seatsAvailable: 3,
      time: '08:15 AM',
      contactNumber: '0301-1234567'
    }
  },
  ADMIN: {
    id: 'usr-demo-admin',
    name: 'GDG Organizer Lead (Admin)',
    cnic: '61101-0000000-0',
    email: 'admin.cloud@gdgislamabad.dev',
    phone: '0300-9990000',
    role: 'ADMIN',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    registeredEvents: ['cloud-devfest-2026', 'build-next-beyond-independence', 'build-with-ai-telenor-velocity'],
    carpoolOptIn: false
  }
};
